name: Schloss
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: gonzohst/test:v0.0.1-beta.1
      options: --user root
    steps:
         - name: Checkout 
           uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
         - name: test
           run: |
             ls -la
             git ls-files --others --exclude-standard
             schloss -t poetry
