name: Schloss
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    container: gonzohst/test:v0.0.1-beta.1
    steps:
         - name: Checkout 
           uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
         - name: test
           run: |
             git config --global --add safe.directory '*'
             schloss -t poetry
